// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_JqMwsEdLOp4FEFAXcKo_VhvsVsPC6AQ',
    appId: '1:541649786978:web:9e64adcff657ab2947193b',
    messagingSenderId: '541649786978',
    projectId: 'scamshield-ee9af',
    authDomain: 'scamshield-ee9af.firebaseapp.com',
    storageBucket: 'scamshield-ee9af.firebasestorage.app',
    measurementId: 'G-3T0R0B5NE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdxUStMGtyTj5MmYXMYhasXkGMpfx7mI',
    appId: '1:541649786978:android:3c9e65b65654627f47193b',
    messagingSenderId: '541649786978',
    projectId: 'scamshield-ee9af',
    storageBucket: 'scamshield-ee9af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKIt9MfT8X452clVhIy4fo3H2kZHSpc2I',
    appId: '1:541649786978:ios:27172970b91a162f47193b',
    messagingSenderId: '541649786978',
    projectId: 'scamshield-ee9af',
    storageBucket: 'scamshield-ee9af.firebasestorage.app',
    iosBundleId: 'com.example.scamshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKIt9MfT8X452clVhIy4fo3H2kZHSpc2I',
    appId: '1:541649786978:ios:27172970b91a162f47193b',
    messagingSenderId: '541649786978',
    projectId: 'scamshield-ee9af',
    storageBucket: 'scamshield-ee9af.firebasestorage.app',
    iosBundleId: 'com.example.scamshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_JqMwsEdLOp4FEFAXcKo_VhvsVsPC6AQ',
    appId: '1:541649786978:web:2cc2685b950ce29c47193b',
    messagingSenderId: '541649786978',
    projectId: 'scamshield-ee9af',
    authDomain: 'scamshield-ee9af.firebaseapp.com',
    storageBucket: 'scamshield-ee9af.firebasestorage.app',
    measurementId: 'G-EZ167NVYHN',
  );
}
